Repository K-Rangers/K-Rangers, pull requests merged in 2025-09, with the labels that each got.

#21 feat: 추천 여행지 컴포넌트 생성
  Frontend/k-rangers-frontend/src/components/RecommendedCard.jsx
  Frontend/k-rangers-frontend/src/components/RecommendedList.jsx
  Frontend/k-rangers-frontend/src/css/AccessChips.module.css
  Frontend/k-rangers-frontend/src/css/RecommendedCard.module.css
  Frontend/k-rangers-frontend/src/css/RecommendedList.module.css
  Frontend/k-rangers-frontend/src/page/MainPage.jsx
Labels: 🚨 High, ✨ Feat

#35 feat: 네비게이션 바 컴포넌트 생성
  Frontend/k-rangers-frontend/package-lock.json
  Frontend/k-rangers-frontend/package.json
  Frontend/k-rangers-frontend/src/App.js
  Frontend/k-rangers-frontend/src/components/BottomNav.jsx
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
  Frontend/k-rangers-frontend/src/css/MainPage.module.css
  Frontend/k-rangers-frontend/src/page/MainPage.jsx
  Frontend/k-rangers-frontend/src/page/Map.jsx
  Frontend/k-rangers-frontend/src/page/MyPage.jsx
  Frontend/k-rangers-frontend/src/page/Save.jsx
Labels: 🚨 High, ✨ Feat

#41 refactor: 네비게이션 컴포넌트 구조 변경
  Frontend/k-rangers-frontend/src/components/BottomNav.jsx
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
  Frontend/k-rangers-frontend/src/page/Save.jsx
Labels: 🛠️ Refactor

#39 [feat] add-swagger-ui
  Backend/.dockerignore
  Backend/.github/workflows/deploy.yml
  Backend/.github/workflows/fly-deploy.yml
  Backend/Dockerfile
  Backend/build.gradle
  Backend/fly.toml
  Backend/src/main/java/org/kmr/backend/config/SecurityConfig.java
  Backend/src/main/resources/application-local.yml
  Backend/src/main/resources/application.properties
  Backend/src/main/resources/application.yml
Labels: 🚨 High, ✨ Feat

#55 [chore] refine-security-rules
  Backend/src/main/java/org/kmr/backend/security/SecurityConfig.java
Labels: 🔧 Chore

#63 refactor: api키 재발급 및 .env.local 파일로 이동
  Frontend/k-rangers-frontend/.gitignore
  Frontend/k-rangers-frontend/src/components/Map.jsx
  Frontend/k-rangers-frontend/src/config/env.js
Labels: 🔥 Urgent, 🛠️ Refactor

#71 chore: PWA 설정
  Frontend/k-rangers-frontend/public/favicon.ico
  Frontend/k-rangers-frontend/public/index.html
  Frontend/k-rangers-frontend/public/logo192.png
  Frontend/k-rangers-frontend/public/logo512.png
  Frontend/k-rangers-frontend/public/manifest.json
  Frontend/k-rangers-frontend/public/service-worker.js
  Frontend/k-rangers-frontend/src/App.css
  Frontend/k-rangers-frontend/src/App.js
  Frontend/k-rangers-frontend/src/index.js
  Frontend/k-rangers-frontend/src/serviceWorkerRegistration.js
Labels: 🚨 High, 🔧 Chore

#72 bug: 빌드 의존성 배열 오류 수정
  Frontend/k-rangers-frontend/src/components/Map.jsx
Labels: 🚨 High, 🐛 Bug

#73 pwa 뷰포트 오류 확인
  Frontend/k-rangers-frontend/src/App.css
Labels: 🚨 High, 🎨 Design

#74 design: ios 상단 노치 여백수정
  Frontend/k-rangers-frontend/src/index.css
Labels: 🚨 High, 🎨 Design

#77 HTML Meta Tag 수정
  .DS_Store
  Frontend/.DS_Store
  Frontend/k-rangers-frontend/public/index.html
  Frontend/k-rangers-frontend/src/App.css
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
  Frontend/k-rangers-frontend/src/css/MapPage.module.css
Labels: 🚨 High, 🔧 Chore

#79 Design : Bottom Nav 디자인 수정 및 불필요한 코드 삭제
  Frontend/k-rangers-frontend/src/App.css
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
  Frontend/k-rangers-frontend/src/css/BottomSheet.module.css
  Frontend/k-rangers-frontend/src/css/MainPage.module.css
  Frontend/k-rangers-frontend/src/css/MapPage.module.css
  Frontend/k-rangers-frontend/src/page/MapPage.jsx
Labels: 🚨 High, 🎨 Design

#83 Design: BottomSheet Position 수정
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
  Frontend/k-rangers-frontend/src/css/BottomSheet.module.css
Labels: 🚨 High, 🎨 Design

#88 Add GitHub Actions workflow for server deployment
  .github/workflows/serverdeploy.yml
Labels: 🚨 High, 🔧 Chore

#90 [design] 네비게이션 바 높이 조정
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
Labels: 🚨 High, 🎨 Design

#92 Add environment file to Docker run command
  .github/workflows/serverdeploy.yml
Labels: 🚨 High, 🔧 Chore

#91 [chore] application.yml
  Backend/src/main/resources/application-prod.yml
  Backend/src/main/resources/application.yml
Labels: 🚨 High, 🔧 Chore

#96 로그인 페이지 생성
  Frontend/k-rangers-frontend/src/App.js
  Frontend/k-rangers-frontend/src/components/BottomNav.jsx
  Frontend/k-rangers-frontend/src/css/Login.module.css
  Frontend/k-rangers-frontend/src/page/LoginPage.jsx
  Frontend/k-rangers-frontend/src/page/MyPage.jsx
Labels: 🚨 High, ✨ Feat

#157 feat: imageUrl add
  .idea/gradle.xml
  Backend/src/main/java/org/kmr/backend/accommodation/domain/Accommodation.java
  Backend/src/main/java/org/kmr/backend/accommodation/dto/response/AccommodationResponse.java
  Backend/src/main/java/org/kmr/backend/attraction/domain/Attraction.java
  Backend/src/main/java/org/kmr/backend/attraction/dto/response/AttractionResponse.java
  Backend/src/main/java/org/kmr/backend/config/DataLoader.java
Labels: 🚨 High, ✨ Feat

#167 feat: 사용자가 쓴 review 모두 조회
  .idea/misc.xml
  .idea/modules/backend.main.iml
  Backend/src/main/java/org/kmr/backend/review/api/ReviewController.java
  Backend/src/main/java/org/kmr/backend/review/dto/MyReviewsResponseDTO.java
  Backend/src/main/java/org/kmr/backend/review/repository/ReviewRepository.java
  Backend/src/main/java/org/kmr/backend/review/service/ReviewService.java
Labels: 🚨 High, ✨ Feat

#168 [fix] server
  Backend/.gitignore
  Backend/src/main/resources/application.yml
Labels: 🚨 High, ✨ Feat

#184 refactor: 코드 리팩토링 및 공통 로직 분리
  .github/pull_request_template.md
  Frontend/k-rangers-frontend/README.md
  Frontend/k-rangers-frontend/package-lock.json
  Frontend/k-rangers-frontend/package.json
  Frontend/k-rangers-frontend/public/index.html
  Frontend/k-rangers-frontend/src/components/AccessChips.jsx
  Frontend/k-rangers-frontend/src/components/AllPostView.jsx
  Frontend/k-rangers-frontend/src/components/BottomSheet.jsx
  Frontend/k-rangers-frontend/src/components/DetailPost.jsx
  Frontend/k-rangers-frontend/src/components/DropDownSelect.jsx
  Frontend/k-rangers-frontend/src/components/Header.jsx
  Frontend/k-rangers-frontend/src/components/HeroSection.jsx
  Frontend/k-rangers-frontend/src/components/Map.jsx
  Frontend/k-rangers-frontend/src/components/RecommendedCard.jsx
  Frontend/k-rangers-frontend/src/components/RecommendedList.jsx
  Frontend/k-rangers-frontend/src/components/RecommendedSection.jsx
  Frontend/k-rangers-frontend/src/css/DetailPost.module.css
  Frontend/k-rangers-frontend/src/css/Map.module.css
  Frontend/k-rangers-frontend/src/data/Options.js
  Frontend/k-rangers-frontend/src/data/dummyAttractions.js
  Frontend/k-rangers-frontend/src/hooks/useAttraction.jsx
  Frontend/k-rangers-frontend/src/page/LoginPage.jsx
  Frontend/k-rangers-frontend/src/page/MainPage.jsx
  Frontend/k-rangers-frontend/src/page/MapPage.jsx
  Frontend/k-rangers-frontend/src/page/MyPage.jsx
  Frontend/k-rangers-frontend/src/page/ReviewWritePage.jsx
  Frontend/k-rangers-frontend/src/store/AttractionStore.jsx
  Frontend/k-rangers-frontend/src/utils/CalcStars.jsx
  Frontend/k-rangers-frontend/src/utils/isOn.jsx
Labels: 🚨 High, 🛠️ Refactor

#186 Bug: Netlify 빌드 중 ESLint 에러 수정
  Frontend/k-rangers-frontend/src/config/env.js
  Frontend/k-rangers-frontend/src/hooks/useAttraction.jsx
Labels: 🚨 High, 🐛 Bug

#189 [fix] application.yml
  Backend/src/main/resources/application.yml
Labels: 🚨 High, 🐛 Bug

#191 [fix] swagger
  Backend/src/main/java/org/kmr/backend/config/SwaggerConfig.java
Labels: 🛠️ Refactor

#192 [refactor] SwaggerConfig
  Backend/src/main/java/org/kmr/backend/config/SwaggerConfig.java
Labels: 🚨 High, 🛠️ Refactor

#193 refactor: BaseURL 수정, 일부 파일 코드 구조 간소화
  Frontend/k-rangers-frontend/src/api/ApiStore.js
  Frontend/k-rangers-frontend/src/components/DropDownSelect.jsx
  Frontend/k-rangers-frontend/src/components/HeroSection.jsx
  Frontend/k-rangers-frontend/src/components/Map.jsx
  Frontend/k-rangers-frontend/src/components/RecommendedCard.jsx
  Frontend/k-rangers-frontend/src/components/RecommendedList.jsx
  Frontend/k-rangers-frontend/src/hooks/useAttraction.jsx
  Frontend/k-rangers-frontend/src/page/MapPage.jsx
Labels: 🚨 High, 🛠️ Refactor

#176 refactor: 회원가입 api 연결, 로그인 페이지 수정, 내정보 리뷰 삭제
  Frontend/k-rangers-frontend/src/api/ApiStore.js
  Frontend/k-rangers-frontend/src/css/Login.module.css
  Frontend/k-rangers-frontend/src/css/MyPage.module.css
  Frontend/k-rangers-frontend/src/css/SignUpPage.module.css
  Frontend/k-rangers-frontend/src/page/LoginPage.jsx
  Frontend/k-rangers-frontend/src/page/MyPage.jsx
  Frontend/k-rangers-frontend/src/page/SignUpPage.jsx
Labels: 🚨 High, 🛠️ Refactor, 🎨 Design

#198 숙소 관련 컴포넌트 작업 및 코드 구조 개선 작업
  Frontend/k-rangers-frontend/src/api/ApiStore.js
  Frontend/k-rangers-frontend/src/components/Accommodation/AccomRecommendedCard.jsx
  Frontend/k-rangers-frontend/src/components/Accommodation/AccomRecommendedList.jsx
  Frontend/k-rangers-frontend/src/components/Accommodation/AllPostAccomCard.jsx
  Frontend/k-rangers-frontend/src/components/AllPostView.jsx
  Frontend/k-rangers-frontend/src/components/Attraction/AttRecommendedCard.jsx
  Frontend/k-rangers-frontend/src/components/Attraction/AttRecommendedList.jsx
  Frontend/k-rangers-frontend/src/components/CardOption/AccessChips.jsx
  Frontend/k-rangers-frontend/src/components/CardOption/AllPostView.jsx
  Frontend/k-rangers-frontend/src/components/CardOption/DetailPost.jsx
  Frontend/k-rangers-frontend/src/components/CardOption/DropDownSelect.jsx
  Frontend/k-rangers-frontend/src/components/CardOption/HeroSection.jsx
  Frontend/k-rangers-frontend/src/css/Accommodation/AccomRecommendedCard.module.css
  Frontend/k-rangers-frontend/src/css/Accommodation/AccomRecommendedList.module.css
  Frontend/k-rangers-frontend/src/css/AllPostPage.module.css
  Frontend/k-rangers-frontend/src/css/AllPostView.module.css
  Frontend/k-rangers-frontend/src/css/Attraction/AttRecommendedList.module.css
  Frontend/k-rangers-frontend/src/css/BottomNav.module.css
  Frontend/k-rangers-frontend/src/css/CardOption/AccessChips.module.css
  Frontend/k-rangers-frontend/src/css/CardOption/AllPostView.module.css
  Frontend/k-rangers-frontend/src/css/CardOption/DetailPost.module.css
  Frontend/k-rangers-frontend/src/css/CardOption/DropDownSelect.module.css
  Frontend/k-rangers-frontend/src/css/CardOption/HeroSection.module.css
  Frontend/k-rangers-frontend/src/css/CardOption/RecommendedCard.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/AllPostPage.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/Login.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/MainPage.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/MapPage.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/MyPage.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/ReviewWritePage.module.css
  Frontend/k-rangers-frontend/src/css/PageCss/SignUpPage.module.css
  Frontend/k-rangers-frontend/src/data/dummyAttractions.js
  Frontend/k-rangers-frontend/src/hooks/useAccommodation.jsx
  Frontend/k-rangers-frontend/src/hooks/useAttraction.jsx
  Frontend/k-rangers-frontend/src/page/AllPostPage.jsx
  Frontend/k-rangers-frontend/src/page/LoginPage.jsx
  Frontend/k-rangers-frontend/src/page/MainPage.jsx
  Frontend/k-rangers-frontend/src/page/MapPage.jsx
  Frontend/k-rangers-frontend/src/page/MyPage.jsx
  Frontend/k-rangers-frontend/src/page/ReviewWritePage.jsx
  Frontend/k-rangers-frontend/src/page/SignUpPage.jsx
  Frontend/k-rangers-frontend/src/utils/FilterByFeatures.jsx
Labels: 🚨 High, 🛠️ Refactor, 🎨 Design, ✨ Feat, 🐛 Bug
